### ISSUE TITLE
Warnings really.. but I thought it is worth a look

### ISSUE THREAD

**Issue by pooran** [xamarin/VervetaCRM#2]
4>  Consider app.config remapping of assembly "System.IO, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoTouch\v1.0\Facades\System.IO.dll] to solve conflict and get rid of warning.
4>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoTouch\v1.0\Facades\System.Runtime.dll] to solve conflict and get rid of warning.
4>  Consider app.config remapping of assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "3.9.0.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoTouch\v1.0\Facades\System.Net.Primitives.dll] to solve conflict and get rid of warning.
4>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "2.0.5.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoTouch\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
4>  Consider app.config remapping of assembly "System.Threading.Tasks, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.11.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoTouch\v1.0\Facades\System.Threading.Tasks.dll] to solve conflict and get rid of warning.

**Comment by jamesmontemagno** [comment]
I always recommend C:/GitHub/\*    for everything as Google APIs are long.

**Comment by ChaseFlorell** [comment]
@jamesmontemagno how do we tell xamarin to use a custom path for those zips?
